import { db, auth } from "../../shared/js/firebase-app.js";
import { builtInAdmins, siteConfig } from "../../shared/js/firebase-config.js";
import { GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { collection, doc, getDoc, setDoc, addDoc, updateDoc, deleteDoc, getDocs, query, orderBy, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const $=id=>document.getElementById(id),provider=new GoogleAuthProvider();let activities=[],adminEmails=[],currentUser=null,regFields=[],fbQuestions=[],search="";const defaultFb=["本次活動內容對我有幫助。","活動安排與流程清楚。","活動讓我有新的學習或體驗。","整體而言，我對本次活動感到滿意。"];
loginBtn.onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){alert("登入失敗："+e.message)}};logoutBtn.onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){loginView.classList.remove("hidden");appView.classList.add("hidden");return}currentUser=user;await loadAdmins();if(!isAdmin(user.email)){alert("這個帳號沒有後台權限："+user.email);signOut(auth);return}loginView.classList.add("hidden");appView.classList.remove("hidden");userInfo.textContent=user.email;resetForm();listenActivities()});
async function loadAdmins(){const ref=doc(db,"settings","admins"),s=await getDoc(ref);adminEmails=s.exists()?(s.data().emails||[]):[];for(const e of builtInAdmins)if(!adminEmails.includes(e))adminEmails.push(e);if(currentUser&&builtInAdmins.includes(currentUser.email))await setDoc(ref,{emails:adminEmails,updatedAt:serverTimestamp()},{merge:true});renderAdmins()}function isAdmin(e){return adminEmails.includes(e)}addAdminBtn.onclick=async()=>{const e=adminEmailInput.value.trim();if(!e||!e.includes("@"))return alert("請輸入正確 Email");if(!adminEmails.includes(e))adminEmails.push(e);await setDoc(doc(db,"settings","admins"),{emails:adminEmails,updatedAt:serverTimestamp()},{merge:true});adminEmailInput.value="";renderAdmins()};function renderAdmins(){if(!adminEmailList)return;adminEmailList.innerHTML=adminEmails.map(e=>`<div class="admin-email-item"><strong>${esc(e)}</strong>${builtInAdmins.includes(e)?"<span>內建</span>":`<button class="ghost-btn" data-remove-admin="${esc(e)}">移除</button>`}</div>`).join("")}
document.addEventListener("click",async e=>{const nav=e.target.closest(".nav-item");if(nav)return showView(nav.dataset.view);const edit=e.target.closest("[data-edit]");if(edit)return editActivity(edit.dataset.edit);const del=e.target.closest("[data-delete]");if(del)return deleteActivity(del.dataset.delete);const copy=e.target.closest("[data-copy]");if(copy)return navigator.clipboard.writeText(copy.dataset.copy).then(()=>alert("已複製連結"));const qr=e.target.closest("[data-qr]");if(qr)return open("https://api.qrserver.com/v1/create-qr-code/?size=500x500&data="+encodeURIComponent(qr.dataset.qr));const regs=e.target.closest("[data-export-regs]");if(regs)return exportRegs(regs.dataset.exportRegs);const fbs=e.target.closest("[data-export-fbs]");if(fbs)return exportFbs(fbs.dataset.exportFbs);const word=e.target.closest("[data-export-word]");if(word)return exportWord(word.dataset.exportWord);const rm=e.target.closest("[data-remove-admin]");if(rm){adminEmails=adminEmails.filter(x=>x!==rm.dataset.removeAdmin);await setDoc(doc(db,"settings","admins"),{emails:adminEmails,updatedAt:serverTimestamp()},{merge:true});renderAdmins()}});
function showView(v){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("view-"+v).classList.remove("hidden");pageTitle.textContent={dashboard:"儀表板",activities:"活動管理",settings:"系統設定"}[v]}newActivityBtn.onclick=()=>{showView("activities");resetForm()};resetBtn.onclick=resetForm;addRegisterFieldBtn.onclick=()=>{regFields.push({label:"新題目",type:"text",required:false,options:[]});renderRegFields()};addFeedbackQuestionBtn.onclick=()=>{fbQuestions.push("新的滿意度題目");renderFbQuestions()};adminSearch.oninput=e=>{search=e.target.value.trim();renderLists()};
function listenActivities(){onSnapshot(query(collection(db,"activities"),orderBy("date","desc")),s=>{activities=s.docs.map(d=>({id:d.id,...d.data()}));statActivities.textContent=activities.length;statRegs.textContent=activities.reduce((n,a)=>n+Number(a.registeredCount||0),0);statFeedbacks.textContent=activities.reduce((n,a)=>n+Number(a.feedbackCount||0),0);renderLists()})}
function renderLists(){const data=activities.filter(a=>!search||(a.title||"").includes(search));const html=data.length?data.map(card).join(""):'<div class="empty">目前沒有活動</div>';$("activityList").innerHTML=html;$("activityList2").innerHTML=html}function card(a){const reg=siteConfig.baseUrl+"frontend/activity.html?id="+a.id,fb=siteConfig.baseUrl+"frontend/feedback.html?id="+a.id;return `<article class="admin-card"><div><div class="admin-card-title">${esc(a.title)} <span class="badge">${statusText(a.status)}</span></div><div class="admin-card-meta">📅 ${esc(a.date||"")} ${esc(a.time||"")}｜📍${esc(a.location||"")}｜報名 ${a.registeredCount||0}/${a.capacity||"不限"}｜回饋 ${a.feedbackCount||0}</div></div><div class="admin-actions"><button class="ghost-btn" data-copy="${reg}">複製報名連結</button><button class="ghost-btn" data-qr="${reg}">報名QR</button><button class="ghost-btn" data-copy="${fb}">複製回饋連結</button><button class="ghost-btn" data-qr="${fb}">回饋QR</button><button class="ghost-btn" data-export-regs="${a.id}">報名CSV</button><button class="ghost-btn" data-export-fbs="${a.id}">回饋CSV</button><button class="ghost-btn" data-export-word="${a.id}">成果Word</button><button class="ghost-btn" data-edit="${a.id}">修改</button><button class="ghost-btn" data-delete="${a.id}">刪除</button></div></article>`}
function resetForm(){$("editId").value="";$("formTitle").textContent="新增活動";$("title").value="";$("date").valueAsDate=new Date();$("time").value="";$("location").value="";$("description").value="";$("capacity").value=0;$("status").value="open";$("published").checked=true;$("feedbackMinWords").value=30;regFields=[];fbQuestions=[...defaultFb];renderRegFields();renderFbQuestions()}function editActivity(id){const a=activities.find(x=>x.id===id);if(!a)return;showView("activities");$("editId").value=id;$("formTitle").textContent="修改活動";$("title").value=a.title||"";$("date").value=a.date||"";$("time").value=a.time||"";$("location").value=a.location||"";$("description").value=a.description||"";$("capacity").value=a.capacity||0;$("status").value=a.status||"open";$("published").checked=a.published!==false;$("feedbackMinWords").value=a.feedbackMinWords||30;regFields=a.registerFields||[];fbQuestions=a.feedbackQuestions||[...defaultFb];renderRegFields();renderFbQuestions()}
function renderRegFields(){$("registerFieldsBox").innerHTML=regFields.map((f,i)=>`<div class="field-item"><div class="field-row"><input class="field reg-label" data-i="${i}" value="${esc(f.label)}"><select class="field reg-type" data-i="${i}"><option value="text" ${f.type==="text"?"selected":""}>簡答</option><option value="textarea" ${f.type==="textarea"?"selected":""}>段落</option><option value="radio" ${f.type==="radio"?"selected":""}>單選</option></select><button type="button" class="ghost-btn reg-remove" data-i="${i}">移除</button></div><label><input type="checkbox" class="reg-required" data-i="${i}" ${f.required?"checked":""}> 必填</label><input class="field reg-options" data-i="${i}" value="${esc((f.options||[]).join(','))}" placeholder="單選選項，用逗號分隔"></div>`).join("")||'<div class="empty">目前沒有自訂題目</div>';bindFieldEvents()}function renderFbQuestions(){$("feedbackQuestionsBox").innerHTML=fbQuestions.map((q,i)=>`<div class="field-item"><div class="field-row"><input class="field fb-question" data-i="${i}" value="${esc(q)}"><span></span><button type="button" class="ghost-btn fb-remove" data-i="${i}">移除</button></div></div>`).join("");bindFieldEvents()}function bindFieldEvents(){document.querySelectorAll(".reg-label").forEach(el=>el.oninput=()=>regFields[el.dataset.i].label=el.value);document.querySelectorAll(".reg-type").forEach(el=>el.onchange=()=>regFields[el.dataset.i].type=el.value);document.querySelectorAll(".reg-required").forEach(el=>el.onchange=()=>regFields[el.dataset.i].required=el.checked);document.querySelectorAll(".reg-options").forEach(el=>el.oninput=()=>regFields[el.dataset.i].options=el.value.split(",").map(x=>x.trim()).filter(Boolean));document.querySelectorAll(".reg-remove").forEach(el=>el.onclick=()=>{regFields.splice(Number(el.dataset.i),1);renderRegFields()});document.querySelectorAll(".fb-question").forEach(el=>el.oninput=()=>fbQuestions[el.dataset.i]=el.value);document.querySelectorAll(".fb-remove").forEach(el=>el.onclick=()=>{fbQuestions.splice(Number(el.dataset.i),1);renderFbQuestions()})}
activityForm.onsubmit=async e=>{e.preventDefault();const data={title:$("title").value.trim(),date:$("date").value,time:$("time").value.trim(),location:$("location").value.trim(),description:$("description").value.trim(),capacity:Number($("capacity").value||0),status:$("status").value,published:$("published").checked,registerFields:regFields,feedbackQuestions:fbQuestions.filter(Boolean),feedbackMinWords:Number($("feedbackMinWords").value||30),updatedAt:serverTimestamp()};if(!data.title||!data.date)return alert("活動名稱和日期必填");if($("editId").value)await updateDoc(doc(db,"activities",$("editId").value),data);else{data.registeredCount=0;data.feedbackCount=0;data.createdAt=serverTimestamp();await addDoc(collection(db,"activities"),cleanUndefined(data))}alert("已儲存");resetForm()};async function deleteActivity(id){if(!confirm("確定刪除此活動？"))return;await deleteDoc(doc(db,"activities",id))}
async function exportRegs(id){const a=activities.find(x=>x.id===id),s=await getDocs(collection(db,"activities",id,"registrations")),rows=s.docs.map(d=>d.data()),heads=["姓名","系級","學號","電話","餐點",...(a.registerFields||[]).map(f=>f.label)],data=rows.map(r=>[r.name,r.department,r.studentId,r.phone,r.meal,...(a.registerFields||[]).map(f=>r.customAnswers?.[f.label]||"")]);downloadCsv(a.title+"_報名名單.csv",[heads,...data])}async function exportFbs(id){const a=activities.find(x=>x.id===id),s=await getDocs(collection(db,"activities",id,"feedbacks")),rows=s.docs.map(d=>d.data()),heads=["姓名","學號",...(a.feedbackQuestions||[]),"心得"],data=rows.map(r=>[r.name,r.studentId,...(a.feedbackQuestions||[]).map(q=>r.ratings?.[q]||""),r.comment]);downloadCsv(a.title+"_回饋資料.csv",[heads,...data])}async function exportWord(id){const a=activities.find(x=>x.id===id),s=await getDocs(collection(db,"activities",id,"feedbacks")),rows=s.docs.map(d=>d.data()),opts=["非常同意","同意","普通","不同意","非常不同意"],qs=a.feedbackQuestions||[],total=rows.length||1;let tr=qs.map((q,i)=>`<tr><td>${i+1}. ${esc(q)}</td>${opts.map(o=>`<td>${Math.round(rows.filter(r=>r.ratings?.[q]===o).length/total*1000)/10}%</td>`).join("")}</tr>`).join(""),comments=rows.map((r,i)=>`<p>${i+1}. ${esc(r.comment||"")}</p>`).join("");downloadFile(a.title+"_活動回饋表.doc",`<!doctype html><meta charset="utf-8"><style>body{font-family:'Microsoft JhengHei';font-size:14pt;line-height:1.8}table{border-collapse:collapse;width:100%}td,th{border:1px solid #333;padding:8px}h1,h2{text-align:center}</style><h2>明新科技大學 健康與諮商中心</h2><h1>資源教室「${esc(a.title)}」活動回饋表</h1><p>時間：${esc(a.date)} ${esc(a.time||"")}</p><p>地點：${esc(a.location||"")}</p><h2 style="text-align:left">一、活動滿意度</h2><table><tr><th>題目</th>${opts.map(o=>`<th>${o}</th>`).join("")}</tr>${tr}</table><h2 style="text-align:left">二、參與活動後，我的心得與感想</h2>${comments}`,"application/msword")}function downloadCsv(name,rows){downloadFile(name,"\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")}function downloadFile(name,content,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function cleanUndefined(obj){
  if(Array.isArray(obj)) return obj.map(cleanUndefined);
  if(obj && typeof obj === "object"){
    const out = {};
    Object.entries(obj).forEach(([k,v]) => {
      if(v !== undefined) out[k] = cleanUndefined(v);
    });
    return out;
  }
  return obj;
}

function statusText(s){return {open:"報名中",feedback:"回饋中",closed:"已結束",draft:"草稿"}[s]||"活動"}function esc(str){return String(str||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
